spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/beers/**
        - id: spring-6-reactive
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/beers/**
        - id: spring-6-reactive-mongo
          uri: http://localhost:8083
          predicates:
            - Path=/api/v3/beers/**

# Nota: Para realizar "troubleshooting" o depuración en el Gateway
#spring:
#  cloud:
#    gateway:
#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true
#logging:
#  level:
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org:springframework.http.server.reactive: trace